package pine

// ATR generates a ValueSeries of average true range
//
// Function ATR returns the RMA of true range ValueSeries.
// True range is already generated by OHLCVSeries.
// True range is max(high - low, abs(high - close[1]), abs(low - close[1])).
//
// Example:
//
// t=time.Time        | 1     |  2    | 3     | 4
// close=ValueSeries  | 13    | 15    | 11    | 19
// high=ValueSeries   | 13.2  | 16    | 11.2  | 19
// low=ValueSeries    | 12.6  | 14.8  | 11    | 19
// TR=ValueSeries     | 0.6   | 3     | 4     | 8
// ATR=ValueSeries    | nil   | nil   | 2.5333| 4.3556
func ATR(tr ValueSeries, l int64) (ValueSeries, error) {
	return RMA(tr, l)
}
